_config_name:
    value: default
_wandb:
    value:
        cli_version: 0.24.0
        e:
            pihy4jyxy5nxsgjcc8ir6vnm3gq921is:
                codePath: scripts\train_burgers_pino.py
                codePathLocal: scripts\train_burgers_pino.py
                email: lei_minghao@sjtu.edu.cn
                executable: C:\Users\MR\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 62617317202328927a9d50c1a276d6de8a690b53
                    remote: https://github.com/LeiMinghaoSJTU/neural-operators.git
                host: DESKTOP-0FTHPKJ
                os: Windows-11-10.0.26100-SP0
                program: d:\document\python\neural operators\scripts\train_burgers_pino.py
                python: CPython 3.12.9
                root: D:\document\python\neural operators
                startedAt: "2026-02-13T02:50:45.186217Z"
                writerId: pihy4jyxy5nxsgjcc8ir6vnm3gq921is
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.9
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
arch:
    value: fno
data:
    value:
        batch_size: 16
        encode_input: false
        encode_output: false
        folder: data
        include_endpoint:
            - true
            - false
        n_tests:
            - 400
        n_train: 800
        spatial_length: 16
        temporal_length: 17
        temporal_subsample: null
        test_batch_sizes:
            - 16
distributed:
    value:
        model_parallel_size: 1
        seed: null
        use_distributed: false
model:
    value:
        channel_mlp_dropout: 0
        channel_mlp_expansion: 0.5
        data_channels: 1
        domain_padding: 0
        factorization: null
        fixed_rank_modes: false
        fno_skip: linear
        hidden_channels: 24
        implementation: factorized
        lifting_channel_ratio: 2
        model_arch: fno
        n_layers: 4
        n_modes:
            - 16
            - 16
        norm: null
        out_channels: 1
        projection_channel_ratio: 2
        rank: 1
        separable: false
        stabilizer: null
        use_channel_mlp: true
n_params_baseline:
    value: null
opt:
    value:
        eval_interval: 1
        gamma: 0.5
        learning_rate: 0.0001
        loss_aggregator: relobralo
        mixed_precision: false
        n_epochs: 100
        scheduler: ReduceLROnPlateau
        scheduler_T_max: 500
        scheduler_patience: 100
        step_size: 60
        testing_loss: l2
        training_loss:
            - equation
            - ic
            - l2
        weight_decay: 0.0001
patching:
    value:
        levels: 0
        padding: 0
        stitching: false
verbose:
    value: true
wandb:
    value:
        entity: null
        group: null
        log: true
        log_output: true
        name: burgers_default_fno_4_[16, 16]_24
        project: null
        sweep: false
